#!/usr/bin/env bash
set -euo pipefail

if [[ "${DOTTY_DRY_RUN:-false}" == "true" ]]; then
    exit 0
fi

remove_ruler_skills() {
    local skills_dir="$1"
    local index="$skills_dir/.dotty-managed-skills.tsv"
    local filtered_index=""
    local kept_skill=false
    local skill_name=""
    local source_dir=""
    local target_dir=""

    [[ -f "$index" ]] || return 0

    filtered_index="$(mktemp "${index}.tmp.XXXXXX")"
    while IFS=$'\t' read -r skill_name source_dir target_dir; do
        if [[ "$source_dir" == */home/.ruler/skills/* ]]; then
            if [[ "$target_dir" == "$skills_dir"/* ]]; then
                rm -rf "$target_dir"
            fi
            continue
        fi

        printf '%s\t%s\t%s\n' "$skill_name" "$source_dir" "$target_dir" >> "$filtered_index"
        if [[ "$skill_name" != "skill_name" ]]; then
            kept_skill=true
        fi
    done < "$index"

    if [[ "$kept_skill" == "true" ]]; then
        mv "$filtered_index" "$index"
    else
        rm -f "$filtered_index"
        rm -f "$index"
    fi
}

remove_ruler_skills "$HOME/.codex/skills"
remove_ruler_skills "$HOME/.claude/skills"

if [[ -f "$HOME/.claude/CLAUDE.md" ]] && head -n 1 "$HOME/.claude/CLAUDE.md" | rg -q 'Generated by dotty from tracked Ruler instruction sources'; then
    rm -f "$HOME/.claude/CLAUDE.md"
fi

if [[ -L "$HOME/.ruler" ]]; then
    rm -f "$HOME/.ruler"
fi
