#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
TARGET_SCRIPT="${PROJECT_ROOT}/.dotty/run.sh"
TEST_PREFIX="sesh-setup-test"

# shellcheck source=/dev/null
source "${PROJECT_ROOT}/tests/tmux-agent-status/testlib.sh"

write_fake_dotty_lib() {
    local path="$1"

    cat > "${path}" <<'EOF'
#!/usr/bin/env bash
title() { :; }
info() { :; }
success() { :; }
warning() { printf '%s\n' "$*" >&2; }
die() { printf '%s\n' "$*" >&2; exit 1; }
create_symlink() { ln -sfn "$1" "$2"; }
EOF
}

run_setup_sesh() {
    local home_dir="$1" repo_dir="$2" dotty_lib="$3"

    HOME="${home_dir}" \
        TARGET_SCRIPT="${TARGET_SCRIPT}" \
        DOTTY_REPO_DIR="${repo_dir}" \
        DOTTY_LIB="${dotty_lib}" \
        DOTTY_COMMAND="update" \
        bash -c 'source "$TARGET_SCRIPT"; setup_sesh'
}

run_symlink_migration_case() {
    local tmp_dir="" home_dir="" base_repo="" overlay_repo="" dotty_lib="" actual_source="" actual_generated=""
    local expected_source="" expected_generated=""

    tmp_dir=$(mktemp -d)
    home_dir="${tmp_dir}/home"
    base_repo="${tmp_dir}/dotfiles"
    overlay_repo="${tmp_dir}/overlay"
    dotty_lib="${tmp_dir}/dotty-lib.sh"

    mkdir -p \
        "${home_dir}/.config" \
        "${home_dir}/.dotty" \
        "${base_repo}/home/.config/sesh" \
        "${overlay_repo}/home/.config/sesh"

    printf '%s\n' 'dir_length = 2' > "${base_repo}/home/.config/sesh/sesh.toml"
    printf '%s\n' 'default_session = "lab"' > "${overlay_repo}/home/.config/sesh/sesh.toml"

    cat > "${home_dir}/.dotty/registry" <<EOF
dotfiles=${base_repo}
overlay=${overlay_repo}
EOF

    ln -s "${base_repo}/home/.config/sesh" "${home_dir}/.config/sesh"
    write_fake_dotty_lib "${dotty_lib}"
    chmod +x "${dotty_lib}"

    run_setup_sesh "${home_dir}" "${base_repo}" "${dotty_lib}"

    assert_equal "setup_sesh replaces a symlinked ~/.config/sesh with a real directory" "1" \
        "$(if [[ -d "${home_dir}/.config/sesh" && ! -L "${home_dir}/.config/sesh" ]]; then printf '1'; else printf '0'; fi)"

    actual_source="$(cat "${base_repo}/home/.config/sesh/sesh.toml")"
    expected_source='dir_length = 2'
    assert_equal "setup_sesh leaves the tracked source fragment untouched" "${expected_source}" "${actual_source}"

    actual_generated="$(cat "${home_dir}/.config/sesh/sesh.toml")"
    expected_generated=$'# Generated by dotty from tracked sesh config fragments.\n# Edit a tracked home/.config/sesh/sesh.toml source, then run `dotty update`.\n\ndir_length = 2\n\ndefault_session = "lab"'
    assert_equal "setup_sesh generates the live config from tracked fragments" "${expected_generated}" "${actual_generated}"

    rm -rf "${tmp_dir}"
}

run_symlink_migration_case
