#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
TARGET_SCRIPT="${PROJECT_ROOT}/.dotty/cleanups/2026-08-remove-ruler-managed-output/run.sh"

# shellcheck source=/dev/null
source "${PROJECT_ROOT}/tests/tmux-agent-status/testlib.sh"

run_removal_case() {
    local temp_dir=""
    local home_dir=""
    local codex_skills=""
    local claude_skills=""

    temp_dir="$(mktemp -d)"
    home_dir="${temp_dir}/home"
    codex_skills="${home_dir}/.codex/skills"
    claude_skills="${home_dir}/.claude/skills"
    mkdir -p \
        "${codex_skills}/native-skill" \
        "${codex_skills}/portable-skill" \
        "${claude_skills}/portable-skill" \
        "${temp_dir}/tracked-ruler"
    ln -s "${temp_dir}/tracked-ruler" "${home_dir}/.ruler"

    printf '%s\n' \
        $'skill_name\tsource_dir\ttarget_dir' \
        $'native-skill\t/repo/home/.codex/skills/native-skill\t'"${codex_skills}/native-skill" \
        $'portable-skill\t/repo/home/.ruler/skills/portable-skill\t'"${codex_skills}/portable-skill" \
        > "${codex_skills}/.dotty-managed-skills.tsv"
    printf '%s\n' \
        $'skill_name\tsource_dir\ttarget_dir' \
        $'portable-skill\t/repo/home/.ruler/skills/portable-skill\t'"${claude_skills}/portable-skill" \
        > "${claude_skills}/.dotty-managed-skills.tsv"
    printf '%s\n' '# Generated by dotty from tracked Ruler instruction sources.' \
        > "${home_dir}/.claude/CLAUDE.md"

    HOME="${home_dir}" "${TARGET_SCRIPT}"

    assert_equal "native Codex skill is preserved" "1" \
        "$(if [[ -d "${codex_skills}/native-skill" ]]; then printf '1'; else printf '0'; fi)"
    assert_equal "Ruler Codex skill is removed" "0" \
        "$(if [[ -e "${codex_skills}/portable-skill" ]]; then printf '1'; else printf '0'; fi)"
    assert_equal "native Codex index row is preserved" "1" \
        "$(rg -c '/home/\.codex/skills/' "${codex_skills}/.dotty-managed-skills.tsv")"
    assert_equal "Ruler Codex index row is removed" "0" \
        "$(if rg -q '/home/\.ruler/skills/' "${codex_skills}/.dotty-managed-skills.tsv"; then printf '1'; else printf '0'; fi)"
    assert_equal "empty Claude managed index is removed" "0" \
        "$(if [[ -e "${claude_skills}/.dotty-managed-skills.tsv" ]]; then printf '1'; else printf '0'; fi)"
    assert_equal "Ruler-generated Claude instructions are removed" "0" \
        "$(if [[ -e "${home_dir}/.claude/CLAUDE.md" ]]; then printf '1'; else printf '0'; fi)"
    assert_equal "Ruler symlink is removed" "0" \
        "$(if [[ -L "${home_dir}/.ruler" ]]; then printf '1'; else printf '0'; fi)"

    rm -rf "${temp_dir}"
}

run_preservation_case() {
    local temp_dir=""
    local home_dir=""

    temp_dir="$(mktemp -d)"
    home_dir="${temp_dir}/home"
    mkdir -p "${home_dir}/.claude" "${home_dir}/.ruler"
    printf '%s\n' '# Custom Claude instructions' > "${home_dir}/.claude/CLAUDE.md"

    HOME="${home_dir}" "${TARGET_SCRIPT}"

    assert_equal "custom Claude instructions are preserved" "1" \
        "$(if [[ -f "${home_dir}/.claude/CLAUDE.md" ]]; then printf '1'; else printf '0'; fi)"
    assert_equal "real Ruler directory is preserved" "1" \
        "$(if [[ -d "${home_dir}/.ruler" ]]; then printf '1'; else printf '0'; fi)"

    rm -rf "${temp_dir}"
}

run_dry_run_case() {
    local temp_dir=""
    local home_dir=""

    temp_dir="$(mktemp -d)"
    home_dir="${temp_dir}/home"
    mkdir -p "${home_dir}/.claude"
    printf '%s\n' '# Generated by dotty from tracked Ruler instruction sources.' \
        > "${home_dir}/.claude/CLAUDE.md"

    HOME="${home_dir}" DOTTY_DRY_RUN=true "${TARGET_SCRIPT}"

    assert_equal "dry-run preserves Ruler-generated output" "1" \
        "$(if [[ -f "${home_dir}/.claude/CLAUDE.md" ]]; then printf '1'; else printf '0'; fi)"

    rm -rf "${temp_dir}"
}

run_removal_case
run_preservation_case
run_dry_run_case
