import { describe, expect, test } from "bun:test";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { rulerCommand } from "../../scripts/ts/sync-ruler";

const repoRoot = resolve(import.meta.dir, "../..");
const syncScript = join(repoRoot, "scripts", "ts", "sync-ruler.ts");

function withTempDir(run: (dir: string) => void) {
  const dir = mkdtempSync(join(tmpdir(), "ruler-sync-"));

  try {
    run(dir);
  } finally {
    rmSync(dir, { force: true, recursive: true });
  }
}

function writeFakeRuler(dir: string) {
  const path = join(dir, "fake-ruler");
  writeFileSync(
    path,
    [
      "#!/usr/bin/env bash",
      "set -euo pipefail",
      "dry_run=false",
      "project_root=",
      "while [[ $# -gt 0 ]]; do",
      "  case \"$1\" in",
      "    --dry-run)",
      "      dry_run=true",
      "      shift",
      "      ;;",
      "    --project-root)",
      "      project_root=\"$2\"",
      "      shift 2",
      "      ;;",
      "    *)",
      "      shift",
      "      ;;",
      "  esac",
      "done",
      "[[ -n \"$project_root\" ]]",
      "if [[ \"$dry_run\" == \"true\" ]]; then",
      "  exit 0",
      "fi",
      "cat > \"$project_root/AGENTS.md\" <<'EOF'",
      "<!-- Generated by Ruler -->",
      "",
      "# Ruler Output",
      "",
      "EOF",
      "cat \"$project_root/.ruler/AGENTS.md\" >> \"$project_root/AGENTS.md\"",
      "if [[ -d \"$project_root/.ruler/skills\" ]]; then",
      "  cat > \"$project_root/CLAUDE.md\" <<'EOF'",
      "<!-- Generated by Ruler -->",
      "",
      "# Claude Output",
      "",
      "EOF",
      "  cat \"$project_root/.ruler/AGENTS.md\" >> \"$project_root/CLAUDE.md\"",
      "  mkdir -p \"$project_root/.agents/skills\" \"$project_root/.claude/skills\"",
      "  cp -R \"$project_root/.ruler/skills/.\" \"$project_root/.agents/skills\"",
      "  cp -R \"$project_root/.ruler/skills/.\" \"$project_root/.claude/skills\"",
      "fi",
      "",
    ].join("\n"),
  );
  chmodSync(path, 0o755);
  return path;
}

function runSync(args: string[]) {
  return Bun.spawnSync(["bun", "run", syncScript, ...args], {
    cwd: repoRoot,
    stderr: "pipe",
    stdout: "pipe",
  });
}

describe("sync-ruler codex-agents", () => {
  test("defaults to Bun for the managed Ruler command", () => {
    expect(rulerCommand("")).toEqual({
      args: [process.execPath, "x", "-y", "@intellectronica/ruler"],
      displayName: "bun x -y @intellectronica/ruler",
    });
  });

  test("validate-only runs Ruler dry-run and does not write output", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const sourcePath = join(dir, "AGENTS.md");
      const outputPath = join(dir, "out", "AGENTS.md");
      writeFileSync(sourcePath, "# Rules\n\n- Prefer focused output.\n");

      const result = runSync([
        "codex-agents",
        "--validate-only",
        "--ruler-bin",
        ruler,
        "--output",
        outputPath,
        "--source",
        sourcePath,
      ]);

      expect(result.exitCode).toBe(0);
      expect(existsSync(outputPath)).toBe(false);
    });
  });

  test("writes dotty-owned output with Ruler body and source provenance", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const missingSource = join(dir, "missing.md");
      const sourcePath = join(dir, "AGENTS.md");
      const outputPath = join(dir, "out", "AGENTS.md");
      writeFileSync(sourcePath, "# Rules\n\n- Prefer focused output.\n");

      const result = runSync([
        "codex-agents",
        "--ruler-bin",
        ruler,
        "--output",
        outputPath,
        "--source",
        missingSource,
        "--source",
        sourcePath,
      ]);

      expect(result.exitCode).toBe(0);

      const generated = readFileSync(outputPath, "utf8");
      expect(generated).toStartWith("# Generated by dotty from tracked Ruler instruction sources.");
      expect(generated).toContain(`Source: ${sourcePath}`);
      expect(generated).not.toContain(`Source: ${missingSource}`);
      expect(generated).toContain("<!-- Generated by Ruler -->");
      expect(generated).toContain("<!-- Source: ");
      expect(generated).toContain("- Prefer focused output.");
    });
  });

  test("fails when every provided source is missing", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const result = runSync([
        "codex-agents",
        "--validate-only",
        "--ruler-bin",
        ruler,
        "--source",
        join(dir, "missing.md"),
      ]);

      expect(result.exitCode).not.toBe(0);
      expect(new TextDecoder().decode(result.stderr)).toContain(
        "No existing Ruler AGENTS.md sources were provided.",
      );
    });
  });

  test("portable mode installs generated skills from the current Codex output path", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const sourcePath = join(dir, "AGENTS.md");
      const skillSourceRoot = join(dir, "skills");
      const skillSourceDir = join(skillSourceRoot, "example-skill");
      const codexAgentsOutput = join(dir, "out", "AGENTS.md");
      const claudeOutput = join(dir, "out", "CLAUDE.md");
      const codexSkillsOutput = join(dir, "out", "codex-skills");
      const claudeSkillsOutput = join(dir, "out", "claude-skills");

      writeFileSync(sourcePath, "# Rules\n\n- Prefer focused output.\n");
      mkdirSync(skillSourceDir, { recursive: true });
      writeFileSync(join(skillSourceDir, "SKILL.md"), "# Example Skill\n");

      const result = runSync([
        "portable",
        "--ruler-bin",
        ruler,
        "--codex-agents-output",
        codexAgentsOutput,
        "--claude-output",
        claudeOutput,
        "--codex-skills-output",
        codexSkillsOutput,
        "--claude-skills-output",
        claudeSkillsOutput,
        "--source",
        sourcePath,
        "--skill-source",
        skillSourceRoot,
      ]);

      expect(result.exitCode).toBe(0);
      expect(readFileSync(join(codexSkillsOutput, "example-skill", "SKILL.md"), "utf8")).toContain(
        "# Example Skill",
      );
      expect(readFileSync(join(claudeSkillsOutput, "example-skill", "SKILL.md"), "utf8")).toContain(
        "# Example Skill",
      );
    });
  });

  test("portable mode removes stale Ruler staging dirs before syncing skills", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const sourcePath = join(dir, "AGENTS.md");
      const skillSourceRoot = join(dir, "skills");
      const skillSourceDir = join(skillSourceRoot, "example-skill");
      const codexAgentsOutput = join(dir, "out", "AGENTS.md");
      const claudeOutput = join(dir, "out", "CLAUDE.md");
      const codexSkillsOutput = join(dir, "out", "codex-skills");
      const claudeSkillsOutput = join(dir, "out", "claude-skills");
      const staleStagingDir = join(codexSkillsOutput, ".tmp-ruler-skill-stale", "partial-skill");
      const unrelatedHiddenDir = join(codexSkillsOutput, ".not-a-ruler-staging-dir");

      writeFileSync(sourcePath, "# Rules\n\n- Prefer focused output.\n");
      mkdirSync(skillSourceDir, { recursive: true });
      mkdirSync(staleStagingDir, { recursive: true });
      mkdirSync(unrelatedHiddenDir, { recursive: true });
      writeFileSync(join(skillSourceDir, "SKILL.md"), "# Example Skill\n");
      writeFileSync(join(staleStagingDir, "SKILL.md"), "# Partial Skill\n");

      const result = runSync([
        "portable",
        "--ruler-bin",
        ruler,
        "--codex-agents-output",
        codexAgentsOutput,
        "--claude-output",
        claudeOutput,
        "--codex-skills-output",
        codexSkillsOutput,
        "--claude-skills-output",
        claudeSkillsOutput,
        "--source",
        sourcePath,
        "--skill-source",
        skillSourceRoot,
      ]);

      expect(result.exitCode).toBe(0);
      expect(existsSync(join(codexSkillsOutput, "example-skill", "SKILL.md"))).toBe(true);
      expect(existsSync(join(codexSkillsOutput, ".tmp-ruler-skill-stale"))).toBe(false);
      expect(existsSync(unrelatedHiddenDir)).toBe(true);
    });
  });

  test("portable mode removes stale managed skills whose source no longer has a skill file", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const sourcePath = join(dir, "AGENTS.md");
      const skillSourceRoot = join(dir, "skills");
      const skillSourceDir = join(skillSourceRoot, "example-skill");
      const staleSourceDir = join(dir, "external-skills", "old-skill");
      const codexAgentsOutput = join(dir, "out", "AGENTS.md");
      const claudeOutput = join(dir, "out", "CLAUDE.md");
      const codexSkillsOutput = join(dir, "out", "codex-skills");
      const claudeSkillsOutput = join(dir, "out", "claude-skills");
      const staleTargetDir = join(claudeSkillsOutput, "old-skill");
      const indexPath = join(claudeSkillsOutput, ".dotty-managed-skills.tsv");

      writeFileSync(sourcePath, "# Rules\n\n- Prefer focused output.\n");
      mkdirSync(skillSourceDir, { recursive: true });
      mkdirSync(staleSourceDir, { recursive: true });
      mkdirSync(staleTargetDir, { recursive: true });
      writeFileSync(join(skillSourceDir, "SKILL.md"), "# Example Skill\n");
      writeFileSync(join(staleTargetDir, "SKILL.md"), "# Old Skill\n");
      writeFileSync(
        indexPath,
        [
          "skill_name\tsource_dir\ttarget_dir",
          `old-skill\t${staleSourceDir}\t${staleTargetDir}`,
          "",
        ].join("\n"),
      );

      const result = runSync([
        "portable",
        "--ruler-bin",
        ruler,
        "--codex-agents-output",
        codexAgentsOutput,
        "--claude-output",
        claudeOutput,
        "--codex-skills-output",
        codexSkillsOutput,
        "--claude-skills-output",
        claudeSkillsOutput,
        "--source",
        sourcePath,
        "--skill-source",
        skillSourceRoot,
      ]);

      expect(result.exitCode).toBe(0);
      expect(existsSync(join(claudeSkillsOutput, "example-skill", "SKILL.md"))).toBe(true);
      expect(existsSync(staleTargetDir)).toBe(false);
      expect(readFileSync(indexPath, "utf8")).not.toContain("old-skill");
    });
  });
});
