import { describe, expect, test } from "bun:test";
import {
  chmodSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "../..");
const syncScript = join(repoRoot, "scripts", "sync-ruler.ts");

function withTempDir(run: (dir: string) => void) {
  const dir = mkdtempSync(join(tmpdir(), "ruler-sync-"));

  try {
    run(dir);
  } finally {
    rmSync(dir, { force: true, recursive: true });
  }
}

function writeFakeRuler(dir: string) {
  const path = join(dir, "fake-ruler");
  writeFileSync(
    path,
    [
      "#!/usr/bin/env bash",
      "set -euo pipefail",
      "dry_run=false",
      "project_root=",
      "while [[ $# -gt 0 ]]; do",
      "  case \"$1\" in",
      "    --dry-run)",
      "      dry_run=true",
      "      shift",
      "      ;;",
      "    --project-root)",
      "      project_root=\"$2\"",
      "      shift 2",
      "      ;;",
      "    *)",
      "      shift",
      "      ;;",
      "  esac",
      "done",
      "[[ -n \"$project_root\" ]]",
      "if [[ \"$dry_run\" == \"true\" ]]; then",
      "  exit 0",
      "fi",
      "cat > \"$project_root/AGENTS.md\" <<'EOF'",
      "<!-- Generated by Ruler -->",
      "",
      "# Ruler Output",
      "",
      "EOF",
      "cat \"$project_root/.ruler/AGENTS.md\" >> \"$project_root/AGENTS.md\"",
      "",
    ].join("\n"),
  );
  chmodSync(path, 0o755);
  return path;
}

function runSync(args: string[]) {
  return Bun.spawnSync(["bun", "run", syncScript, ...args], {
    cwd: repoRoot,
    stderr: "pipe",
    stdout: "pipe",
  });
}

describe("sync-ruler codex-agents", () => {
  test("validate-only runs Ruler dry-run and does not write output", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const sourcePath = join(dir, "AGENTS.md");
      const outputPath = join(dir, "out", "AGENTS.md");
      writeFileSync(sourcePath, "# Rules\n\n- Prefer focused output.\n");

      const result = runSync([
        "codex-agents",
        "--validate-only",
        "--ruler-bin",
        ruler,
        "--output",
        outputPath,
        "--source",
        sourcePath,
      ]);

      expect(result.exitCode).toBe(0);
      expect(existsSync(outputPath)).toBe(false);
    });
  });

  test("writes dotty-owned output with Ruler body and source provenance", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const missingSource = join(dir, "missing.md");
      const sourcePath = join(dir, "AGENTS.md");
      const outputPath = join(dir, "out", "AGENTS.md");
      writeFileSync(sourcePath, "# Rules\n\n- Prefer focused output.\n");

      const result = runSync([
        "codex-agents",
        "--ruler-bin",
        ruler,
        "--output",
        outputPath,
        "--source",
        missingSource,
        "--source",
        sourcePath,
      ]);

      expect(result.exitCode).toBe(0);

      const generated = readFileSync(outputPath, "utf8");
      expect(generated).toStartWith("# Generated by dotty from tracked Ruler instruction sources.");
      expect(generated).toContain(`Source: ${sourcePath}`);
      expect(generated).not.toContain(`Source: ${missingSource}`);
      expect(generated).toContain("<!-- Generated by Ruler -->");
      expect(generated).toContain("<!-- Source: ");
      expect(generated).toContain("- Prefer focused output.");
    });
  });

  test("fails when every provided source is missing", () => {
    withTempDir((dir) => {
      const ruler = writeFakeRuler(dir);
      const result = runSync([
        "codex-agents",
        "--validate-only",
        "--ruler-bin",
        ruler,
        "--source",
        join(dir, "missing.md"),
      ]);

      expect(result.exitCode).not.toBe(0);
      expect(new TextDecoder().decode(result.stderr)).toContain(
        "No existing Ruler AGENTS.md sources were provided.",
      );
    });
  });
});
