#!/usr/bin/env bun

import { parse, stringify } from "smol-toml@1.4.2";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

type TomlValue =
  | string
  | number
  | boolean
  | TomlValue[]
  | { [key: string]: TomlValue };

type TomlDocument = Record<string, TomlValue>;
type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
type JsonObject = Record<string, JsonValue>;

function parseArgs(argv: string[]) {
  const [mode, ...rest] = argv;
  const sources: string[] = [];
  let output = "";

  for (let index = 0; index < rest.length; index += 1) {
    const token = rest[index];
    if (token === "--output") {
      output = rest[index + 1] ?? "";
      index += 1;
      continue;
    }

    if (token === "--source") {
      const source = rest[index + 1];
      if (source) {
        sources.push(resolve(source));
      }
      index += 1;
      continue;
    }
  }

  if ((mode !== "agents" && mode !== "config" && mode !== "hooks") || !output) {
    throw new Error("Usage: sync_codex.ts <agents|config|hooks> --output <path> --source <path>...");
  }

  return {
    mode,
    output: resolve(output),
    sources,
  };
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function clone<T>(value: T): T {
  return structuredClone(value);
}

function loadToml(path: string): TomlDocument {
  if (!existsSync(path)) {
    return {};
  }

  const text = readFileSync(path, "utf8");
  const value = parse(text);

  if (!isObject(value)) {
    throw new Error(`Expected TOML table in ${path}`);
  }

  return value as TomlDocument;
}

function mergeToml(base: TomlDocument, overlay: TomlDocument): TomlDocument {
  const merged = clone(base);

  for (const [key, value] of Object.entries(overlay)) {
    if (Array.isArray(value)) {
      merged[key] = clone(value);
      continue;
    }

    if (isObject(value) && isObject(merged[key])) {
      merged[key] = mergeToml(merged[key] as TomlDocument, value as TomlDocument);
      continue;
    }

    merged[key] = clone(value as TomlValue);
  }

  return merged;
}

function loadJson(path: string): JsonObject {
  if (!existsSync(path)) {
    return {};
  }

  const parsed = JSON.parse(readFileSync(path, "utf8")) as JsonValue;
  if (!isObject(parsed)) {
    throw new Error(`Expected JSON object in ${path}`);
  }

  return parsed as JsonObject;
}

function buildHeader(lines: string[]) {
  return `${lines.map((line) => `# ${line}`).join("\n")}\n\n`;
}

function writeManagedFile(outputPath: string, body: string, headerLines: string[]) {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${buildHeader(headerLines)}${body}`, "utf8");
}

function syncAgents(outputPath: string, sourcePaths: string[]) {
  const existingSources = sourcePaths.filter((source) => existsSync(source));
  const sections = existingSources
    .map((source) => readFileSync(source, "utf8").trim())
    .filter(Boolean);

  const body = sections.length > 0 ? `${sections.join("\n\n---\n\n")}\n` : "";
  writeManagedFile(outputPath, body, [
    "Generated by dotty from tracked Codex instruction fragments.",
    "Edit one of these source files, then run `dotty update`.",
    ...existingSources.map((source) => `Source: ${source}`),
  ]);
}

function syncConfig(outputPath: string, sourcePaths: string[]) {
  let merged = clone(loadToml(outputPath));
  const existingSources = sourcePaths.filter((source) => existsSync(source));

  for (const source of existingSources) {
    merged = mergeToml(merged, loadToml(source));
  }

  writeManagedFile(outputPath, stringify(merged), [
    "Generated by dotty from tracked Codex config fragments.",
    "Tracked fragments are deep-merged over the live local file; tables merge recursively and arrays are replaced by later sources.",
    "Edit one of these source files, then run `dotty update`.",
    ...existingSources.map((source) => `Source: ${source}`),
  ]);
}

function syncHooks(outputPath: string, sourcePaths: string[]) {
  const existingSources = sourcePaths.filter((source) => existsSync(source));
  const highestPrioritySource = existingSources.at(-1);

  if (!highestPrioritySource) {
    return;
  }

  const hooks = loadJson(highestPrioritySource);

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${JSON.stringify(hooks, null, 2)}\n`, "utf8");
}

function main() {
  const { mode, output, sources } = parseArgs(process.argv.slice(2));

  if (mode === "agents") {
    syncAgents(output, sources);
    return;
  }

  if (mode === "hooks") {
    syncHooks(output, sources);
    return;
  }

  syncConfig(output, sources);
}

main();
