#!/usr/bin/env bun

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { tmpdir } from "node:os";

type Mode = "codex-agents";

type ParsedArgs = {
  mode: Mode;
  output: string;
  rulerBin: string;
  sources: string[];
  validateOnly: boolean;
};

function parseArgs(argv: string[]): ParsedArgs {
  const [mode, ...rest] = argv;
  const sources: string[] = [];
  let output = "";
  let rulerBin = process.env.RULER_BIN ?? "";
  let validateOnly = false;

  for (let index = 0; index < rest.length; index += 1) {
    const token = rest[index];

    if (token === "--output") {
      output = rest[index + 1] ?? "";
      index += 1;
      continue;
    }

    if (token === "--ruler-bin") {
      rulerBin = rest[index + 1] ?? "";
      index += 1;
      continue;
    }

    if (token === "--source") {
      const source = rest[index + 1];
      if (source) {
        sources.push(resolve(source));
      }
      index += 1;
      continue;
    }

    if (token === "--validate-only") {
      validateOnly = true;
      continue;
    }
  }

  if (mode !== "codex-agents" || (!output && !validateOnly)) {
    throw new Error(
      "Usage: sync-ruler.ts codex-agents [--validate-only] --output <path> [--ruler-bin <path>] --source <path> ...",
    );
  }

  return {
    mode,
    output: output ? resolve(output) : "",
    rulerBin,
    sources,
    validateOnly,
  };
}

function existingFiles(paths: string[]) {
  return paths.filter((path) => existsSync(path) && statSync(path).isFile());
}

function buildHeader(lines: string[]) {
  return `${lines.map((line) => `# ${line}`).join("\n")}\n\n`;
}

function renderRulerAgentsSource(sourcePaths: string[]) {
  const sources = existingFiles(sourcePaths);

  if (sources.length === 0) {
    throw new Error("No existing Ruler AGENTS.md sources were provided.");
  }

  const sections = sources
    .map((source) => {
      const body = readFileSync(source, "utf8").trim();
      return body ? `<!-- Source: ${source} -->\n\n${body}` : "";
    })
    .filter(Boolean);

  return {
    body: `${sections.join("\n\n---\n\n")}\n`,
    sources,
  };
}

function rulerCommand(rulerBin: string) {
  if (rulerBin) {
    return {
      args: [rulerBin],
      displayName: rulerBin,
    };
  }

  return {
    args: ["npx", "-y", "@intellectronica/ruler"],
    displayName: "npx -y @intellectronica/ruler",
  };
}

function runRuler(stagingRoot: string, validateOnly: boolean, rulerBin: string) {
  const command = rulerCommand(rulerBin);
  const args = [
    ...command.args,
    "apply",
    ...(validateOnly ? ["--dry-run"] : []),
    "--agents",
    "codex",
    "--local-only",
    "--no-mcp",
    "--no-skills",
    "--no-subagents",
    "--no-gitignore",
    "--no-backup",
    "--project-root",
    stagingRoot,
  ];
  const result = Bun.spawnSync(args, {
    stderr: "pipe",
    stdout: "pipe",
  });

  if (result.exitCode === 0) {
    return;
  }

  const stdout = new TextDecoder().decode(result.stdout).trim();
  const stderr = new TextDecoder().decode(result.stderr).trim();
  const details = [stdout, stderr].filter(Boolean).join("\n");

  throw new Error(`Ruler command failed: ${command.displayName}\n${details}`);
}

function stageRulerProject(sourcePaths: string[]) {
  const { body, sources } = renderRulerAgentsSource(sourcePaths);
  const stagingRoot = mkdtempSync(join(tmpdir(), "dotty-ruler-codex-"));
  const rulerDir = join(stagingRoot, ".ruler");

  mkdirSync(rulerDir, { recursive: true });
  writeFileSync(join(rulerDir, "AGENTS.md"), body, "utf8");
  writeFileSync(
    join(rulerDir, "ruler.toml"),
    ['default_agents = ["codex"]', "", "[agents.codex]", "enabled = true", ""].join("\n"),
    "utf8",
  );

  return { sources, stagingRoot };
}

function syncCodexAgents(
  outputPath: string,
  sourcePaths: string[],
  validateOnly: boolean,
  rulerBin: string,
) {
  const { sources, stagingRoot } = stageRulerProject(sourcePaths);

  try {
    runRuler(stagingRoot, validateOnly, rulerBin);

    if (validateOnly) {
      return;
    }

    const generatedPath = join(stagingRoot, "AGENTS.md");
    if (!existsSync(generatedPath)) {
      throw new Error(`Ruler did not generate ${generatedPath}`);
    }

    const generatedBody = readFileSync(generatedPath, "utf8");
    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(
      outputPath,
      `${buildHeader([
        "Generated by dotty from tracked Ruler instruction sources.",
        "Edit one of these source files, then run `dotty update`.",
        ...sources.map((source) => `Source: ${source}`),
      ])}${generatedBody}`,
      "utf8",
    );
  } finally {
    rmSync(stagingRoot, { force: true, recursive: true });
  }
}

function main() {
  const { mode, output, rulerBin, sources, validateOnly } = parseArgs(process.argv.slice(2));

  if (mode === "codex-agents") {
    syncCodexAgents(output, sources, validateOnly, rulerBin);
  }
}

main();
