#!/usr/bin/env bun

import { parse, stringify } from "smol-toml@1.4.2";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const MANAGED_KEYS = [
  "model",
  "personality",
  "sandbox_mode",
  "approval_policy",
  "tui.theme",
  "features.codex_hooks",
] as const;

type TomlValue =
  | string
  | number
  | boolean
  | TomlValue[]
  | { [key: string]: TomlValue };

type TomlDocument = Record<string, TomlValue>;

function parseArgs(argv: string[]) {
  const [mode, ...rest] = argv;
  const sources: string[] = [];
  let output = "";

  for (let index = 0; index < rest.length; index += 1) {
    const token = rest[index];
    if (token === "--output") {
      output = rest[index + 1] ?? "";
      index += 1;
      continue;
    }

    if (token === "--source") {
      const source = rest[index + 1];
      if (source) {
        sources.push(resolve(source));
      }
      index += 1;
      continue;
    }
  }

  if ((mode !== "agents" && mode !== "config") || !output) {
    throw new Error("Usage: sync_codex.ts <agents|config> --output <path> --source <path>...");
  }

  return {
    mode,
    output: resolve(output),
    sources,
  };
}

function isObject(value: unknown): value is TomlDocument {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function loadToml(path: string): TomlDocument {
  if (!existsSync(path)) {
    return {};
  }

  const text = readFileSync(path, "utf8");
  const value = parse(text);

  if (!isObject(value)) {
    throw new Error(`Expected TOML table in ${path}`);
  }

  return value;
}

function getPath(document: TomlDocument, dottedKey: string): TomlValue | undefined {
  let current: unknown = document;

  for (const part of dottedKey.split(".")) {
    if (!isObject(current) || !(part in current)) {
      return undefined;
    }
    current = current[part];
  }

  return current as TomlValue;
}

function setPath(document: TomlDocument, dottedKey: string, value: TomlValue) {
  const parts = dottedKey.split(".");
  let current: TomlDocument = document;

  for (const part of parts.slice(0, -1)) {
    const existing = current[part];
    if (!isObject(existing)) {
      current[part] = {};
    }
    current = current[part] as TomlDocument;
  }

  current[parts.at(-1)!] = value;
}

function buildHeader(lines: string[]) {
  return `${lines.map((line) => `# ${line}`).join("\n")}\n\n`;
}

function writeFile(outputPath: string, body: string, headerLines: string[]) {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${buildHeader(headerLines)}${body}`, "utf8");
}

function syncAgents(outputPath: string, sourcePaths: string[]) {
  const existingSources = sourcePaths.filter((source) => existsSync(source));
  const sections = existingSources
    .map((source) => readFileSync(source, "utf8").trim())
    .filter(Boolean);

  const body = sections.length > 0 ? `${sections.join("\n\n---\n\n")}\n` : "";
  writeFile(outputPath, body, [
    "Generated by dotty from tracked Codex instruction fragments.",
    "Edit one of these source files, then run `dotty update`.",
    ...existingSources.map((source) => `Source: ${source}`),
  ]);
}

function syncConfig(outputPath: string, sourcePaths: string[]) {
  const merged = structuredClone(loadToml(outputPath));
  const existingSources = sourcePaths.filter((source) => existsSync(source));

  for (const source of existingSources) {
    const fragment = loadToml(source);
    for (const key of MANAGED_KEYS) {
      const value = getPath(fragment, key);
      if (value !== undefined) {
        setPath(merged, key, value);
      }
    }
  }

  writeFile(outputPath, stringify(merged), [
    "Generated by dotty from tracked Codex config fragments.",
    "Managed keys are overlaid from the source files below; all other keys are preserved from the live local file.",
    "Edit one of these source files, then run `dotty update`.",
    ...existingSources.map((source) => `Source: ${source}`),
  ]);
}

function main() {
  const { mode, output, sources } = parseArgs(process.argv.slice(2));

  if (mode === "agents") {
    syncAgents(output, sources);
    return;
  }

  syncConfig(output, sources);
}

main();
