#!/usr/bin/env bun

import { mergeWith } from "es-toolkit@1.45.1";
import { parse, stringify } from "smol-toml@1.4.2";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

type TomlValue =
  | string
  | number
  | boolean
  | TomlValue[]
  | { [key: string]: TomlValue };

type TomlDocument = Record<string, TomlValue>;
type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
type JsonObject = Record<string, JsonValue>;
type Mode = "agents" | "config" | "hooks";
type HookAction = JsonObject & { type: string };
type HookEventEntry = JsonObject & { hooks: HookAction[] };
type HookMap = Record<string, HookEventEntry[]>;

function parseArgs(argv: string[]) {
  const [mode, ...rest] = argv;
  const sources: string[] = [];
  let output = "";
  let validateOnly = false;

  for (let index = 0; index < rest.length; index += 1) {
    const token = rest[index];
    if (token === "--output") {
      output = rest[index + 1] ?? "";
      index += 1;
      continue;
    }

    if (token === "--source") {
      const source = rest[index + 1];
      if (source) {
        sources.push(resolve(source));
      }
      index += 1;
      continue;
    }

    if (token === "--validate-only") {
      validateOnly = true;
      continue;
    }
  }

  if ((mode !== "agents" && mode !== "config" && mode !== "hooks") || (!output && !validateOnly)) {
    throw new Error(
      "Usage: sync-codex.ts <agents|config|hooks> [--validate-only] --output <path> --source <path>...",
    );
  }

  return {
    mode: mode as Mode,
    output: output ? resolve(output) : "",
    sources,
    validateOnly,
  };
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function clone<T>(value: T): T {
  return structuredClone(value);
}

function loadToml(path: string): TomlDocument {
  if (!existsSync(path)) {
    return {};
  }

  return parseTomlDocument(readFileSync(path, "utf8"), path);
}

function parseTomlDocument(text: string, context: string): TomlDocument {
  const value = parse(text);

  if (!isObject(value)) {
    throw new Error(`Expected TOML table in ${context}`);
  }

  return value as TomlDocument;
}

function replaceArrays(_targetValue: unknown, sourceValue: unknown) {
  if (Array.isArray(sourceValue)) {
    return clone(sourceValue);
  }

  return undefined;
}

function loadJson(path: string): JsonObject {
  if (!existsSync(path)) {
    return {};
  }

  return parseJsonObject(readFileSync(path, "utf8"), path);
}

function parseJsonObject(text: string, context: string): JsonObject {
  const parsed = JSON.parse(text) as JsonValue;
  if (!isObject(parsed)) {
    throw new Error(`Expected JSON object in ${context}`);
  }

  return parsed as JsonObject;
}

function buildHeader(lines: string[]) {
  return `${lines.map((line) => `# ${line}`).join("\n")}\n\n`;
}

function writeManagedFile(outputPath: string, body: string, headerLines: string[]) {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, `${buildHeader(headerLines)}${body}`, "utf8");
}

function existingSources(sourcePaths: string[]) {
  return sourcePaths.filter((source) => existsSync(source));
}

function renderAgents(sourcePaths: string[]) {
  const sources = existingSources(sourcePaths);
  const sections = sources.map((source) => readFileSync(source, "utf8").trim()).filter(Boolean);
  const body = sections.length > 0 ? `${sections.join("\n\n---\n\n")}\n` : "";

  return { body, sources };
}

function syncAgents(outputPath: string, sourcePaths: string[], validateOnly: boolean) {
  const { body, sources } = renderAgents(sourcePaths);

  if (validateOnly) {
    return;
  }

  writeManagedFile(outputPath, body, [
    "Generated by dotty from tracked Codex instruction fragments.",
    "Edit one of these source files, then run `dotty update`.",
    ...sources.map((source) => `Source: ${source}`),
  ]);
}

function renderConfig(outputPath: string, sourcePaths: string[], validateOnly: boolean) {
  let merged = validateOnly ? {} : clone(loadToml(outputPath));
  const sources = existingSources(sourcePaths);

  for (const source of sources) {
    merged = mergeWith(merged, loadToml(source), replaceArrays) as TomlDocument;
  }

  const body = stringify(merged);
  parseTomlDocument(body, "generated Codex config");

  return { body, sources };
}

function syncConfig(outputPath: string, sourcePaths: string[], validateOnly: boolean) {
  const { body, sources } = renderConfig(outputPath, sourcePaths, validateOnly);

  if (validateOnly) {
    return;
  }

  writeManagedFile(outputPath, body, [
    "Generated by dotty from tracked Codex config fragments.",
    "Tracked fragments are deep-merged over the live local file; tables merge recursively and arrays are replaced by later sources.",
    "Edit one of these source files, then run `dotty update`.",
    ...sources.map((source) => `Source: ${source}`),
  ]);
}

function validateHookAction(entry: JsonValue, context: string): HookAction {
  if (!isObject(entry)) {
    throw new Error(`Expected hook action object in ${context}`);
  }

  if (typeof entry.type !== "string" || entry.type.length === 0) {
    throw new Error(`Expected hook action with string type in ${context}`);
  }

  if (entry.type === "command" && typeof entry.command !== "string") {
    throw new Error(`Expected command hook with string command in ${context}`);
  }

  return clone(entry as HookAction);
}

function validateHookEventEntry(entry: JsonValue, context: string): HookEventEntry {
  if (!isObject(entry)) {
    throw new Error(`Expected hook event entry object in ${context}`);
  }

  if (!Array.isArray(entry.hooks)) {
    throw new Error(`Expected hook event entry with hooks array in ${context}`);
  }

  const hooks = entry.hooks.map((action, index) =>
    validateHookAction(action, `${context}.hooks[${index}]`),
  );

  return {
    ...(clone(entry as JsonObject)),
    hooks,
  };
}

function loadHooks(path: string) {
  const parsed = loadJson(path);
  const rawHooks = parsed.hooks;

  if (!isObject(rawHooks)) {
    throw new Error(`Expected JSON object with hooks table in ${path}`);
  }

  const hooks: HookMap = {};

  for (const [eventName, eventHooks] of Object.entries(rawHooks)) {
    if (!Array.isArray(eventHooks)) {
      throw new Error(`Expected hook array for event "${eventName}" in ${path}`);
    }

    hooks[eventName] = eventHooks.map((entry, index) =>
      validateHookEventEntry(entry, `${path} (${eventName}[${index}])`),
    );
  }

  return hooks;
}

function renderHooks(sourcePaths: string[]) {
  const sources = existingSources(sourcePaths);
  const hooks: HookMap = {};

  for (const source of sources) {
    const parsed = loadHooks(source);
    for (const [eventName, eventHooks] of Object.entries(parsed)) {
      hooks[eventName] ??= [];
      hooks[eventName].push(...eventHooks.map((entry) => clone(entry)));
    }
  }

  const body = `${JSON.stringify({ hooks }, null, 2)}\n`;
  parseJsonObject(body, "generated Codex hooks");

  return body;
}

function syncHooks(outputPath: string, sourcePaths: string[], validateOnly: boolean) {
  const body = renderHooks(sourcePaths);

  if (validateOnly) {
    return;
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, body, "utf8");
}

function main() {
  const { mode, output, sources, validateOnly } = parseArgs(process.argv.slice(2));

  if (mode === "agents") {
    syncAgents(output, sources, validateOnly);
    return;
  }

  if (mode === "hooks") {
    syncHooks(output, sources, validateOnly);
    return;
  }

  syncConfig(output, sources, validateOnly);
}

main();
